### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by lingnand** [denysvitali/sonos-web-rs#1]
I'm new to rust, and can't get over this installation problem.

Starting with `rustup`, I installed `stable` rust, and then `cargo run` generates this error

~~~
error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/lingnan/.cargo/registry/src/github.com-1ecc6299db9ec823/yansi-0.3.2/src/lib.rs:1:32
  |
1 | #![cfg_attr(feature="nightly", feature(const_fn))]
  |                                ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `yansi`.
warning: build failed, waiting for other jobs to finish...
~~~

If I switch to `nightly` rust, it still couldn't work

~~~
error: `std::sync::atomic::AtomicBool::new` is not yet stable as a const fn
   --> /Users/lingnan/.cargo/registry/src/github.com-1ecc6299db9ec823/yansi-0.3.2/src/lib.rs:479:57
    |
479 | #[cfg(feature="nightly")] static DISABLED: AtomicBool = AtomicBool::new(false);
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: in Nightly builds, add `#![feature(const_atomic_bool_new)]` to the crate attributes to enable
~~~

It might be something terribly obvious, but I just couldn't figure it out given my near-zero rust experience. Any help is greatly appreciated. Thanks.

**Comment by denysvitali** [comment]
Thanks for your interest in this project.

It isn't a fault from your end: unfortunately since this project is based on Rust Nightly (due to Rocket.rs requirements), a more recent version of Rust may break the compatibility when older dependencies are used.  
I `cargo update`d the Cargo.lock file, and it should work now 😃 

Feel free to comment / reopen the issue if it still doesn't work (I had the exact same problem, now it works)

**Comment by lingnand** [comment]
That works. Thanks for the very fast response!
